export type Tool = {
  slug: string;
  title: string;
  short: string;
  description: string;
  hint: string;
  kind: 'compress' | 'crop' | 'convert' | 'resize';
  icon: string;
  target?: number;
  ratio?: number;
  width?: number;
  height?: number;
  format?: 'image/jpeg' | 'image/png' | 'image/webp';
  accept: string;
  faqs: [string, string][];
};
const images = 'image/jpeg,image/png,image/webp';
export const tools: Tool[] = [
  { slug: 'compress-image', title: 'Kompres foto', short: 'Kompres foto', description: 'Kecilkan ukuran foto JPG, PNG, atau WebP. Pilih batas ukuran file atau atur kualitasnya sendiri.', hint: 'Ukuran lebih kecil, tetap enak dilihat.', kind: 'compress', icon: 'compress', accept: images, faqs: [['Apakah format foto berubah?', 'Hasil kompresi disimpan sebagai JPG. Area transparan akan menjadi putih. Foto asli di perangkat Anda tetap utuh.'], ['Apakah dimensi foto berubah?', 'Kompresi biasa mempertahankan dimensi foto. Jika memilih target KB, dimensi dapat diperkecil agar hasil memenuhi batas ukuran.']] },
  ...[100, 200, 500].map((target): Tool => ({ slug: `compress-image-${target}kb`, title: `Kompres foto ke ${target} KB`, short: `Kompres ${target} KB`, description: `Untuk formulir yang membatasi ukuran foto hingga ${target} KB. Pilih foto, kompres, lalu simpan hasilnya.`, hint: `Pas untuk batas upload ${target} KB.`, kind: 'compress', icon: 'compress', target, accept: images, faqs: [[`Apakah hasil selalu di bawah ${target} KB?`, `Tool mencari kualitas JPG tertinggi yang memenuhi batas ${target} × 1.024 byte. Jika perlu, dimensi foto ikut diperkecil. Jika batas tidak dapat dicapai, pesan kesalahan akan ditampilkan.`], ['Apakah kualitas foto berkurang?', 'Kompresi JPG dapat mengurangi detail. Periksa preview hasil sebelum digunakan, terutama untuk foto dengan teks kecil. File asli tidak diubah.']] })),
  ...[{ label: '2×3', slug: '2x3', ratio: 2 / 3, width: 236, height: 354 }, { label: '3×4', slug: '3x4', ratio: 3 / 4, width: 354, height: 472 }, { label: '4×6', slug: '4x6', ratio: 4 / 6, width: 472, height: 708 }].map((p): Tool => ({ slug: `resize-foto-${p.slug}`, title: `Buat pas foto ${p.label}`, short: `Foto ${p.label}`, description: `Atur potongan pas foto ${p.label}, pilih batas KB, lalu download JPG dalam satu proses. Dimensi pas foto tetap terjaga.`, hint: 'Pas foto untuk urusan administrasi.', kind: 'crop', icon: 'crop', ratio: p.ratio, width: p.width, height: p.height, accept: images, faqs: [['Bagaimana cara mengatur potongan foto?', 'Geser foto pada preview atau gunakan pengatur posisi horizontal, vertikal, dan zoom. Preview menunjukkan potongan yang akan disimpan.'], ['Berapa ukuran hasil dalam piksel?', `Ukuran awal ${p.width} × ${p.height} piksel. Anda dapat memilih rasio 2×3, 3×4, atau 4×6 tanpa pindah alat. Batas KB diterapkan setelah crop tanpa mengecilkan dimensi hasil.`]] })),
  { slug: 'resize-image', title: 'Resize foto dalam piksel atau persen', short: 'Resize bebas', description: 'Atur lebar dan tinggi foto, atau perkecil berdasarkan persen. Pilih JPG, PNG, atau WebP dan simpan hasilnya di perangkat Anda.', hint: 'Sesuaikan dimensi tanpa mengubah file asli.', kind: 'resize', icon: 'crop', accept: images, faqs: [['Apakah wajah akan berubah bentuk?', 'Kunci rasio menjaga proporsi gambar. Buka kunci hanya jika Anda memang membutuhkan lebar dan tinggi yang berbeda dari rasio asli.'], ['Bisakah memperbesar gambar?', 'Bisa hingga 32 megapiksel dan 16.384 piksel per sisi. Memperbesar tidak mengembalikan detail yang tidak ada pada foto asli.']] },
  { slug: 'png-to-jpg', title: 'PNG ke JPG', short: 'PNG ke JPG', description: 'Ubah gambar PNG menjadi JPG. Kalau latarnya transparan, pilih warna untuk menggantikannya.', hint: 'Ubah format, beres dalam satu langkah.', kind: 'convert', icon: 'convert', format: 'image/jpeg', accept: 'image/png', faqs: [['Apa yang terjadi dengan latar transparan?', 'JPG tidak mendukung transparansi. Bagian transparan diganti dengan warna latar yang Anda pilih; warna awalnya putih.'], ['Apakah ukuran gambar berubah?', 'Dimensi gambar tetap sama. Ukuran file dapat berubah karena JPG menggunakan kompresi.']] },
  { slug: 'jpg-to-png', title: 'JPG ke PNG', short: 'JPG ke PNG', description: 'Ubah foto JPG menjadi PNG dengan dimensi yang sama. Foto asli tetap tersimpan di perangkat Anda.', hint: 'Format PNG, tanpa instal aplikasi.', kind: 'convert', icon: 'convert', format: 'image/png', accept: 'image/jpeg', faqs: [['Apakah konversi meningkatkan kualitas?', 'Konversi mempertahankan gambar yang sudah ada. Detail yang hilang saat kompresi JPG tidak dapat dikembalikan.'], ['Mengapa file PNG lebih besar?', 'PNG menyimpan gambar tanpa kompresi lossy tambahan. Untuk foto, hasil PNG biasanya lebih besar daripada JPG.']] },
  ...[{ slug: 'jpg-to-webp', from: 'JPG', to: 'WebP', accept: 'image/jpeg', format: 'image/webp' }, { slug: 'png-to-webp', from: 'PNG', to: 'WebP', accept: 'image/png', format: 'image/webp' }, { slug: 'webp-to-jpg', from: 'WebP', to: 'JPG', accept: 'image/webp', format: 'image/jpeg' }, { slug: 'webp-to-png', from: 'WebP', to: 'PNG', accept: 'image/webp', format: 'image/png' }].map((p): Tool => ({ slug: p.slug, title: `${p.from} ke ${p.to}`, short: `${p.from} ke ${p.to}`, description: `Konversi ${p.from} menjadi ${p.to} langsung di browser. Periksa hasil dan download tanpa mengirim gambar ke server.`, hint: 'Format yang sesuai untuk aplikasi Anda.', kind: 'convert', icon: 'convert', format: p.format as Tool['format'], accept: p.accept, faqs: [['Apakah dimensinya berubah?', 'Tidak. Konversi mempertahankan dimensi gambar asli. Gambar animasi akan menjadi gambar diam.'], ['Apakah transparansi dipertahankan?', 'PNG dan WebP mendukung transparansi. JPG mengisi bagian transparan dengan warna latar pilihan Anda.']] })),
];
export const featured = ['compress-image-200kb', 'resize-foto-3x4', 'resize-foto-4x6', 'png-to-jpg'];
